version: 2.1
jobs: 
  build:
     docker: 
       - image: alpine:3.7
     working_directory: ~/brightevent-frontend-app
     steps: 
      - checkout
      - run:
          name: install yarn
          command: apk add yarn
      - run:
          name: install dependency
          command: yarn install
      - run: 
          name: run tests
          command: yarn test
workflows:
  version: 2
  commit:
     jobs:
      - build 