version: 2.1
jobs: 
  build:
     docker: 
       - image: alpine:3.7
     working_directory: ~/brightevent-frontend-app
     steps: 
      - checkout
      - run:
         name: install yarn
         command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore-cache: 
         name: restore yarn cache
         keys: 
           - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
        name: install dependencies
        command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths: ~/.cache/yarn    
      - run: 
          name: run tests
          command: yarn test
workflows:
  version: 2
  commit:
     jobs:
      - build 