
export const actionTypes = {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER:'LOGOUT_USER',
  CREATE_EVENT:'CREATE_EVENT',
  EDIT_EVENT:'EDIT_EVENT',
  GET_ALL_EVENTS:'GET_ALL_EVENTS',
  GET_EVENT_PAGES:'GET_EVENT_PAGES',
  SEARCH_EVENT:'SEARCH_EVENT',
  DELETE_EVENT:'DELETE_EVENT',
  CREATE_RSVP:'CREATE_RSVP'
};
